[package]
name = "rust-game-engine"
version = "0.1.0"
authors = ["sallaben <steven.allaben@gmail.com>", "paranoidandroid81 <smdkorst@gmail.com>"]
edition = "2018"

[dependencies]
gfx-hal = "0.2.1"
rendy = "0.3.1"
winit = "0.19.1"
