[package]
name = "rust-game-engine"
version = "0.1.0"
authors = ["sallaben <steven.allaben@gmail.com>", "paranoidandroid81 <mpk44@pitt.edu>"]
edition = "2018"

[dependencies]
rendy = "0.3.2"
log = "0.4.6"
simple_logger = "1.3.0"
arrayvec = "0.4.10"

